Add git-cherry-pick pipeline
chainguard-dev/melange pull request #1278
Opened 2024-06-13 20:35 UTC by krishjainx

cc @smoser

2024-06-13 21:01 UTC, smoser requested changes
Its a start.
We want the `git-cherry-pick` to work with the `git checkout`.
So maybe even it should be added to the git-checkout pipeline instead.

The difficulty will be in fetching hashes of commits.

extending the checkout seems to me to be acceptable and probably easier.

It might look something like this:

```yaml
pipeline:
  - uses: git-checkout
    with:
      expected-commit: 73d317384c9225e46d66444f93b46f0fbe7084ef
      repository: https://git.code.sf.net/p/zsh/code
      tag: zsh-${{package.version}}
      cherry-picks: |
          9dcaf78997508f45105f11a28932fcb6b113d27e
          f57ad185b31e927bffc8e24566ef0584bddce5bb
```

2024-06-20 19:58 UTC, smoser requested changes
you can/should add some tests to the git-checkout test in e2e/

You but before doing that, i'd verify it works on some "main" inputs that you think should work.

2024-06-20 19:58 UTC, smoser commented on pkg/build/pipelines/git-checkout.yaml
> +                # ...
you have to do something here.
git fetch that branch.

2024-06-20 20:53 UTC, smoser commented on pkg/build/pipelines/git-checkout.yaml
> +                vr git fetch origin $branch:$branch
you have to return failure if this fails.

2024-06-20 20:54 UTC, smoser requested changes
can you add some tests to e2e checkout test?

2024-06-20 20:54 UTC, smoser commented on pkg/build/pipelines/git-checkout.yaml
> +                vr git fetch origin $branch:$branch
and ideally we don't 'git fetch main' N times for each cherry-pick.  so if we've seen the same branch we can skip.

2024-06-21 02:39 UTC, jonjohnsonjr commented on pkg/build/pipelines/git-checkout.yaml
> +  cherrypicks:
I don't have a hugely strong opinion here, but git always hyphenates "cherry-pick", so I would expect this to be hyphenated as well.

2024-06-21 12:03 UTC, smoser reviewed
I think this looks pretty good.
there are a couple things that need updating, but I like it.

Could you look in wolfi and find a patch that is a cherry-pick and verify it actually works ?

2024-06-21 12:17 UTC, rawlingsj requested changes
Are we able to provide some info on the use cases where we'd use this cherry pick?  Just wondering how this may affect our existing automation or is there need for new automation to update / remove cherry picked commits?

2024-06-21 17:56 UTC, smoser commented on pkg/build/pipelines/git-checkout.yaml
> +            local cherry-pick="$8"
can't have - in variable name.

2024-06-21 18:38 UTC, smoser commented
@rawlingsj ,

Maybe this helps to illustrate the goal.  It wont work for all patches we carry, but for many patches we just cherry pick upstream fixes.  The wolfi package [argon2](https://github.com/wolfi-dev/os/blob/main/argon2.yaml) has an upstream cherry pick in patches/fix-cross-compilation.patch.

I'd like to change that as shown below:

```diff
diff --git a/argon2.yaml b/argon2.yaml
index 27c6ae4fc..521868adc 100644
--- a/argon2.yaml
+++ b/argon2.yaml
@@ -19,10 +19,9 @@ pipeline:
       depth: 1
       tag: ${{package.version}}
       expected-commit: 62358ba2123abd17fccf2a108a301d4b52c01a7c
-
-  - uses: patch
-    with:
-      patches: fix-cross-compilation.patch
+      cherry-picks: |
+        # fix cross compilation
+        master/cd1c1d8d204e4ec4557e358013567c097cb70562
 
   - runs: |
       make -j$(nproc) OPTTARGET=none ARGON2_VERSION=${{package.version}}
```

The value in the new syntax is:
1. easier to create - developer can just paste an upstream commit id into the yaml file and see if 'make package/argon2.yaml' works.  Much easier than checking out git, applying the patch and creating patch/<file>.patch.

2. easier to review - the reviewer knows that the patch was not inadvertantly changed.

3. no duplication needed - we don't have to have a local copy of the patch, its stored in upstream git, we just reference it.

4. At some point (maybe this is what you were asking about), I can see automation on package update that looks at the cherry picks and drops any that
are included in the new release.

2024-06-21 18:43 UTC, smoser commented on pkg/build/pipelines/git-checkout.yaml
> +      cat > "/tmp/cherry-pick" << "END_CHERRY_PICKS"
lets use mktemp.

```
cpickf=$(mktemp) || { echo "failed mktemp"; exit 1; }
cat > "$cpickf" <<"END_CHERRY_PICKS"
...

main ...
rm -f "$pickf"
```

2024-06-21 18:49 UTC, smoser requested changes

2024-06-21 18:49 UTC, smoser commented on pkg/build/pipelines/git-checkout.yaml
> +                vr env GIT_AUTHOR_NAME="Melange Build" GIT_AUTHOR_EMAIL="melange-build@cgr.dev" GIT_COMMITTER_DATE="$SOURCE_EPOCH_DATE" git cherry-pick -x "$hash" || {
make this line shorter. 

GIT_AUTHOR_NAME=.... \
    GIT_COMMITER_DATE=... \
    git cherry-pick -x

2024-06-21 18:49 UTC, smoser commented on pkg/build/pipelines/git-checkout.yaml
> +            vr git clone "--origin=$remote" $flags \
can you add `--config=advice.detachedHead=false` here ?
that will silence that big git detached head message.

2024-06-24 15:06 UTC, rawlingsj commented
> Maybe this helps to illustrate the goal.

This helps a lot and makes sense.  We can automate the removal of these patches in the future too.

One thought and not a blocker... I wonder if we should have a field that forces people to add reason for the patch rather than rely on people adding a comment?

I.e. 

```yaml
      cherry-picks: |
        cd1c1d8d204e4ec4557e358013567c097cb70562: fix cross compilation
```

something like?

2024-06-24 15:09 UTC, rawlingsj commented
Mind you it's a bit brittle. 

Alternatively, like the data / range feature, could we add a struct to capture commit sha's and reference that in the cherry-pick?  Am just thinking or ways we can build better automation and presubmit checks in the future?

2024-06-24 15:30 UTC, xnox commented
> Mind you it's a bit brittle.
> 
> Alternatively, like the data / range feature, could we add a struct to capture commit sha's and reference that in the cherry-pick? Am just thinking or ways we can build better automation and presubmit checks in the future?

shouldn't cherry-picks auto fall off? i thought cherry-pick / rebase is a no-op, if a given commit is already included. I would have hoped we can do something more declarative checks such as `git tag --contains <sha1> <tag>` to check if a given patch has already been incorporated into a given tag.

2024-06-24 15:37 UTC, smoser commented
@rawlingsj ,
Its easy enough to take/require some text next to the cherry pick, and it more tightly associates comment with sha than comments above the sha.  So i do like that.  I'm happy to support or require at your request.

wrt data / range.  I think I'd prefer to avoid that unless you have a use case in mind that benefits you.  If the `data` that is being provided is not specifically typed/keyed to cherry picks, I'd think it would actually make things harder.

I _would_ like to one day get to 'cherry-picks' being a proper list data type rather than carriage return separated string. but as it is right now with shell pipelines and simple variable expansion in the pipeline (${{inputs.xxxx}}) having a list isn't possible.  ("someday" i think we have pipelines in a language that has less footguns and can properly handle list/dict/int/string types).

2024-06-24 17:17 UTC, rawlingsj commented
> shouldn't cherry-picks auto fall off? i thought cherry-pick / rebase is a no-op, if a given commit is already included. I would have hoped we can do something more declarative checks such as git tag --contains <sha1> <tag> to check if a given patch has already been incorporated into a given tag.

yeah I was thinking about cleaning up the melange yaml to auto remove old cherry-picked commits.

> I would like to one day get to 'cherry-picks' being a proper list data type rather than carriage return separated string. but as it is right now with shell pipelines and simple variable expansion in the pipeline (${{inputs.xxxx}}) having a list isn't possible. ("someday" i think we have pipelines in a language that has less footguns and can properly handle list/dict/int/string types).

yeah sorry, this was what I was thinking as opposed to reusing the existing data/range.  I.e having a cherry-pick struct, but agree it's going to take more work.  

I think it's ok though would probably want to run it past @imjasonh or @jonjohnsonjr for a final approval.

2024-06-24 22:14 UTC, krishjainx commented on e2e-tests/test-git-checkout.yaml
> +      [ "$hash" = "$expected_hash" ]
Make this [ "$hash" != "$expected_hash" ]?

2024-06-24 22:15 UTC, krishjainx commented on pkg/build/pipelines/git-checkout.yaml
> +            fi
ACK

2024-06-24 22:37 UTC, krishjainx commented on e2e-tests/test-git-checkout.yaml
> +      [ "$hash" = "$expected_hash" ]
Will rebase btw

2024-06-24 23:24 UTC, jonjohnsonjr commented
A bunch of the CI checks got renamed, do you mind rebasing?

2024-06-25 13:13 UTC, smoser commented
@jonjohnsonjr or @imjasonh ,

I'm going to push 're-run' on the failed 'Build packages' for gitsign and guac, and I think it will fix the problem.  They were both CVE problems:

guac (fixed [here](https://github.com/wolfi-dev/os/pull/22618))

    (1/1) Installing guac (0.7.2-r2)
    OK: 91 MiB in 15 packages
    🔎 Scanning "packages/x86_64/guac-0.7.2-r2.apk"
    └── 📄 /usr/bin/guaccollect
            📦 github.com/hashicorp/go-retryablehttp v0.7.4 (go-module)
                Medium CVE-2024-6104 GHSA-v6v8-xj6m-xwqh fixed in 0.7.7
     
    Error: Process completed with exit code 1.

gitsign (fixed [here](https://github.com/wolfi-dev/os/pull/22585)):

    🔎 Scanning "packages/x86_64/gitsign-0.10.2-r2.apk"
    └── 📄 /usr/bin/gitsign
            📦 github.com/hashicorp/go-retryablehttp v0.7.5 (go-module)
                Medium CVE-2024-6104 GHSA-v6v8-xj6m-xwqh fixed in 0.7.7
     
    🔎 Scanning "packages/x86_64/gitsign-config-0.10.2-r2.apk"
    ✅ No vulnerabilities found
    🔎 Scanning "packages/x86_64/gitsign-credential-cache-0.10.2-r2.apk"
    ✅ No vulnerabilities found
    Error: Process completed with exit code 1.

If I understand these correctly, I don't think it makes sense to gate melange development on wolfi's ability to keep up with CVE.

2024-06-25 13:37 UTC, xnox commented
> @jonjohnsonjr or @imjasonh ,
> 
> I'm going to push 're-run' on the failed 'Build packages' for gitsign and guac, and I think it will fix the problem. They were both CVE problems:
> 
> guac (fixed [here](https://github.com/wolfi-dev/os/pull/22618))
> 
> ```
> (1/1) Installing guac (0.7.2-r2)
> OK: 91 MiB in 15 packages
> 🔎 Scanning "packages/x86_64/guac-0.7.2-r2.apk"
> └── 📄 /usr/bin/guaccollect
>         📦 github.com/hashicorp/go-retryablehttp v0.7.4 (go-module)
>             Medium CVE-2024-6104 GHSA-v6v8-xj6m-xwqh fixed in 0.7.7
>  
> Error: Process completed with exit code 1.
> ```
> 
> gitsign (fixed [here](https://github.com/wolfi-dev/os/pull/22585)):
> 
> ```
> 🔎 Scanning "packages/x86_64/gitsign-0.10.2-r2.apk"
> └── 📄 /usr/bin/gitsign
>         📦 github.com/hashicorp/go-retryablehttp v0.7.5 (go-module)
>             Medium CVE-2024-6104 GHSA-v6v8-xj6m-xwqh fixed in 0.7.7
>  
> 🔎 Scanning "packages/x86_64/gitsign-config-0.10.2-r2.apk"
> ✅ No vulnerabilities found
> 🔎 Scanning "packages/x86_64/gitsign-credential-cache-0.10.2-r2.apk"
> ✅ No vulnerabilities found
> Error: Process completed with exit code 1.
> ```
> 
> If I understand these correctly, I don't think it makes sense to gate melange development on wolfi's ability to keep up with CVE. Maybe we can ignore or not run the cve check?

sadness.....

in theory there shouldn't be any cves in wolfi =/

2024-06-25 13:45 UTC, smoser commented
@krishjainx , the failed test is because we put anoterh commit on the 2.0 branch .  The tests would have to be updated to address that.  But... we actually didn't want that commit (the "exciting file content" commit) on the 2.0 branch, as the goal was to cherry pick it back from main.

I think apply this patch:
```patch
diff --git a/e2e-tests/test-fixtures/create-git-repo b/e2e-tests/test-fixtures/create-git-repo
index d6644e5..8e0d429 100755
--- a/e2e-tests/test-fixtures/create-git-repo
+++ b/e2e-tests/test-fixtures/create-git-repo
@@ -86,17 +86,20 @@ v git checkout --quiet main
 v wfile README "mainline stuff"
 v gcommit -m "mainline stuff" README
 
-v git checkout --quiet main
-v wfile README "mainline stuff 2"
-v gcommit -m "mainline stuff 2" README
-
-v git checkout --quiet -b 2.x main^
+v git checkout --quiet -b 2.x main
 v wfile README "2.0-release content"
 v gcommit -m "release 2.0" README
 v gtag 2.0
 v gtag --annotate --message="Release 2.0" 2.0-annotated HEAD
 
 v git checkout --quiet main
+v wfile README "mainline stuff 2"
+v gcommit -m "mainline stuff 2" README
+
+v wfile file1.txt "exciting file contents"
+v git add file1.txt
+v gcommit -m "finally add file1.txt" file1.txt
+
 
 v cd "$startd"
 v mv "$workdir/.git" "$dest"
```

I think that might "just work".

Then... the only thing remaining on this PR i think is that @rawlingsj asked for the ability to put comments on the individual patch

2024-06-25 13:57 UTC, smoser commented
Then... the only thing remaining on this PR i think is that @rawlingsj asked for the ability to put comments on the individual patches line.

I think for now what make sense is
1. newline separated patch lines (as we have)
2. comments allowed anywhere after a '#', completely ignored (as we have)
3. empty lines (or full comment lines) ignored
4. patch lines of either `[branch/]commit: comment` or `[branch/]commit comment`.  Basically, do we want a ':' that feels more yaml like or no colon which doesn't put up a facade that this content is yaml (its not!).  I leant towards the second, but am fine to do the first if others think so.

I think we might as well require a comment on a cherry pick.  It can be anything, we're not going to enforce form, just _something_.  Wolfi will put either CVE or other content there.


So, remaining for this PR
1. update to require the comment (update your test accordingly)
2. I think it makes sense to put a PIPELINES-GIT.md file in docs update documentation (probably put in examples/git-checkout.yaml) 

thank you for your patience on this. good work.b

2024-06-25 14:08 UTC, rawlingsj commented
nice - yeah personally I quite like
```
[branch/]commit: comment here
```

2024-06-25 16:16 UTC, krishjainx commented
TODO(Krish):

doc.
enforce comment on cherry pick (and ':')

2024-06-25 18:01 UTC, smoser commented
Just a comment here.. real world use case. 
I just saw [CVE-2024-4032](https://nvd.nist.gov/vuln/detail/CVE-2024-4032) come up on a python-3.10 [PR](https://github.com/wolfi-dev/os/pull/22542) that I was doing and it could be fixed with this:

```diff
diff --git a/python-3.10.yaml b/python-3.10.yaml
index 2d29b2a15..d89858c3b 100644
--- a/python-3.10.yaml
+++ b/python-3.10.yaml
@@ -1,7 +1,7 @@
 package:
   name: python-3.10
   version: 3.10.14
-  epoch: 3
+  epoch: 4
   description: "the Python programming language"
   copyright:
     - license: PSF-2.0
@@ -48,6 +48,8 @@ pipeline:
       expected-commit: 976ea78599d71f22e9c0fefc2dc37c1d9fc835a4
       repository: https://github.com/python/cpython.git
       tag: v${{package.version}}
+      cherry-picks: |
+        3.10/c62c9e518b784fe44432a3f4fc265fb95b651906: CVE-2024-4032
 
   - name: Force use of system libraries
     runs: |
```

2024-06-25 18:42 UTC, smoser commented on pkg/build/pipelines/git-checkout.yaml
> +      List of cherry picks to apply
this needs information here on how it is formatted.

```
New line separated entries.  Lines can be empty. Any content on a line after `#` is ignored.
After removing comments, each line is of the form:

    [branch/]commit-id: comment explaining cherry-pick

comment and commit-id are required.  branch on origin that
the commit lives should be provided or git is not guaranteed to
have a reference to the commit-id.

Example: ...

```
cherry-picks: |
    3.10/62705d869aca4055e8a96e2ed4f9013e9917c661:

2024-06-25 19:03 UTC, smoser commented on docs/PIPELINES-GIT.md
> +      tag: v${{package.version}}
fill this in to '3.10.14' otherwise it is time-dependent.

2024-06-25 19:06 UTC, krishjainx commented on docs/PIPELINES-GIT.md
> +      tag: v${{package.version}}
🫡

2024-06-25 19:13 UTC, smoser commented on pkg/build/pipelines/git-checkout.yaml
> +        3.10/62705d869aca4055e8a96e2ed4f9013e9917c661:
needs indentation.

2024-06-25 19:13 UTC, smoser commented on pkg/build/pipelines/git-checkout.yaml
> +      List of cherry picks to apply. New line separated entries.  Lines can be empty. Any content on a line after `#` is ignored.
break this line (only because you need to fix the indent below)

2024-06-25 19:39 UTC, smoser commented on pkg/build/pipelines/git-checkout.yaml
> +          3.10/62705d869aca4055e8a96e2ed4f9013e9917c661:
this line needs indenting.

for the multi-line yaml thing, the body has to be indentned.

```yaml
cherry-picks: |
  3.10/62705d869aca4055e8a96e2ed4f9013e9917c661: You need a comment here.
```

2024-06-25 19:46 UTC, smoser approved these changes
:+1: :fireworks:

2024-06-25 19:48 UTC, smoser commented
ugh. @rawlingsj is on holiday, but i'm pretty sure his feedback was addressed.

2024-06-25 19:59 UTC, merged