add npm and update prefix location
chainguard-dev/melange pull request #1527
Opened 2024-10-02 08:35 UTC by kranurag7

- out of the box `npm` is not installed with nodejs so pipeline cannot be used as of now. 

- prefix was once changed before via https://github.com/chainguard-dev/melange/pull/863 but if we go with `/usr` then `npm` is not able to detect the installs. It is looking for installed deps under `/usr/local/lib/node_modules` but this pipelines installs things under `/usr/lib/node_modules` 

```bash
/ # npm root -g
/usr/local/lib/node_modules
/ # npm install vite -g

added 10 packages in 3s

3 packages are looking for funding
  run `npm fund` for details
/ # ls /usr/local/lib/node_modules/
vite
```

In wolfi, some `npm install` are using `-prefix ${{targets.destdir}}/usr/local/` prefix. 
ref: https://github.com/wolfi-dev/os/blob/16217a5581667f12cc28a592eef03fec13f98ffb/lerna.yaml#L28 and https://github.com/wolfi-dev/os/blob/16217a5581667f12cc28a592eef03fec13f98ffb/renovate.yaml#L29

but some are also using `-prefix ${{targets.destdir}}/usr` 
ref: https://github.com/wolfi-dev/os/blob/16217a5581667f12cc28a592eef03fec13f98ffb/playwright.yaml#L23

thinking about it from placing binary perspective, it makes sense that we choose `/usr` because we put most binaries in `/usr/bin` but if we go with `/usr/local` as well then that should be good as well considering it's there in PATH.
```bash
/ # echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```
from libraries perspective, for e.g. while packaging express, we need to use `/usr/local` considering `npm root -g`

2024-10-02 09:32 UTC, kranurag7 commented
test failure seems unrelated to this change. 

```bash
 2024/10/02 08:56:05 INFO /usr/bin/python3.12 -c "from setuptools import version": PASS uses=python/import
FAIL:  py3-pandas-test.yaml
make: *** [Makefile:155: test-e2e] Error 1
Error: Process completed with exit code 2.
```

2024-10-02 13:46 UTC, EyeCantCU requested changes

2024-10-02 13:46 UTC, EyeCantCU commented on pkg/build/pipelines/npm/install.yaml
> +    default: "${{targets.contextdir}}/usr/local/"
Thank you for looking at this but distributions shouldn't use `/usr/local`. Anything we provide should land in `/usr` as we are the vendor. `/usr/local` is reserved for the end user. See FHS guidelines here: https://refspecs.linuxfoundation.org/FHS_3.0/fhs/index.html

2024-10-06 12:51 UTC, EyeCantCU commented
Would you update the PR description and title to match the change?

2024-10-06 13:02 UTC, kranurag7 commented
> Would you update the PR description and title to match the change?

Thanks RJ, I've updated that.

2024-12-13 16:00 UTC, maxgio92 approved these changes

2025-02-03 14:27 UTC, EyeCantCU approved these changes

2025-02-03 14:27 UTC, merged